language: node_js
node_js: 8
sudo: required
before_script:
- npm install -g polymer-cli
- npm install -g bower
- polymer install --variants
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
  sauce_connect: true
script:
- polymer lint cookie-details.html
- xvfb-run polymer test polymer test --plugin local
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then polymer test --plugin sauce --job-name
  "cookie-details:${TRAVIS_BRANCH}" --build-number=${TRAVIS_BUILD_NUMBER}; fi
cache:
  directories:
  - node_modules
after_success:
- node tasks/ci.js
env:
  global:
  - secure: pg7aC1lLObTdUiFZIMSvSI5/vlt5qkfMBnwYrDc/u+BOEmC44fXm2OHOxzegpr11UUjbbjaV2tcS9v4TmSHqlrQWJ14DKIhlkw8dd6Er4HAxYYggM3V1+4BsWqEM6aG0q8zA7gxXuoDLgag1qyykfq+0jeFdUBotlSQySKuBfEf0Jv05Xxd/dihmB3ivhHpftl1R7rgrZUo4tZ+PVnCpT96t9owNaFboXnDopYW/lHV0Evf86W8dmf454CBCq685vcT57LzVicXq5F4lEIf5LWSJ7KymP83j+4LUFEVn3HhJo1XjVWRRUQNKeAeSI/IhXj+Wm9yceu/FG/kl5Qs7Guir2VSV3c/TDstMxMYgaj9nN9e+MpN7do+Zj4rqrHhVUkQ6aYB4Q/TFQ10HcyEscorP5VKFdKJCMciCTudFQHAEa6TksgYWmjngAIrExEMWee7P7iguy3boG5GxK4jsFXEc+CRkINsfLb7Iy/Hu2vtvEXpQ0L8hdAUxhD3Etaf4EU3Gpodfvv5wDoaGgCEK8nRfoFlKctUmBfEm5lhzYr2tXdZtdZTtSgm4KthLf7TboQ7hhNkttuPp09F+HoBwMWGD7xB3OEX7Kb9Gts9+eVHogDstEF3XrKNaJYCu+mbwH5qHbKO31AwqG+PC+Q7Pu7eWIcndRPPHH0REfI/CJmo=
  - secure: p9CooqIbWpN5EydDpOVI3+O3rnh24ZGOqj2hWTEDMVIZITe1puqczV6+1GZ/8zEr/5PXqVmnMs0uYC966/zYVXkNTd0uK7LWagwEA0xIvFs3WbqwoQOQTPRbewFGVcwzbLHFNR8go2EE6T4IryjxjO+rySdzaxOuBXP4ysBGsyZwp9RqnOkuF8SPe/JaWmdVynrSi7R6uCDVyzwRNU024XTkdCjpdpFj7BtpdZ7nN0lP/aoE1E1lW7r28fcwBiHNrliiTnMolJYfd79+L3nW7Lz2bHcyAkQC//sTy94jCqqve4tpE7wirLIwYsOxBRosbV52MG4IMoKt3dOFfXSJ9lTgX+XV3SMD+SQhvdNVx/vPkPWK3rwQrLFhxYkGRb0axSicxzFSLReX8SdXXQ6yDea6KiIM2BDEUAqN1JN+qtg5/noioisk+McOaZ3kY8pdAMeg9Z0bZDJ84YfkSgBTC9PEQsop0Jzm/9Zq/s4a2v2byG5Wi53LWdyPqC6f6ULZ7MIa2lqhhrCMENh/EWqOgAPoEaMa1jRXT9se47RNvXEGifGWopzuhk3CCh7IkHHTES11Uwja7bSgi/sDSjhdk68HnM7v5BVLOlB6n2gMVPYb3Xv86WHryTAJP/L2odM4whynR51lsroPuVnLYMKLqyCzYVbZlQ/bJH7cGLVxrnQ=
