/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   cookie-details.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.

declare namespace UiElements {

  /**
   * A cookie details view.
   */
  class CookieDetails {

    /**
     * A cookie to render
     */
    cookie: object|null|undefined;

    /**
     * Sends non-bubbling `delete-cookie` event to the parent element to perform
     * delete action.
     */
    _deleteCookie(): void;

    /**
     * Sends non-bubbling `edit-cookie` event to the parent element to perform
     * edit action.
     */
    _editCookie(): void;
  }
}

declare global {

  interface HTMLElementTagNameMap {
    "cookie-details": UiElements.CookieDetails;
  }
}

export {};
