/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   cookie-details.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

import {html, css, LitElement} from 'lit-element';

import {ArcResizableMixin} from '@advanced-rest-client/arc-resizable-mixin/arc-resizable-mixin.js';

declare namespace UiElements {

  /**
   * A cookie details view.
   */
  class CookieDetails {

    /**
     * A cookie to render
     */
    cookie: object|null|undefined;
    render(): any;

    /**
     * Sends non-bubbling `delete-cookie` event to the parent element to perform
     * delete action.
     */
    _deleteCookie(): void;

    /**
     * Sends non-bubbling `edit-cookie` event to the parent element to perform
     * edit action.
     */
    _editCookie(): void;
  }
}

declare global {

  interface HTMLElementTagNameMap {
    "cookie-details": UiElements.CookieDetails;
  }
}
